services:
  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379:6379'
    environment:
      REDIS_ARGS: '--appendonly yes'
    volumes:
      - '~/docker-data/semanticcahce-redis:/data'
