spring.application.name=semanticcahce

spring.main.web-application-type=none
spring.main.banner-mode=off


spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.root=warn

logging.level.org.springframework.ai.vectorstore.redis=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n


